a1_py:
  # My goal is to get a program that compiles with python 3.5
  image: python:3.6.9
  before_script:
    - apt-get install graphviz -y
    - pip install -r requirements.txt
  script:
    - python main.py
    # Figure this out next assignment
    # - xvfb-run python3 solution.py
  artifacts:
    paths:
      - '*.png'
    expire_in: 1 weeks